<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>ptl</string>
    </array>

    <key>name</key>
    <string>Pony.JS Template Language</string>

    <key>patterns</key>
    <array>
        <dict>
			<key>match</key>
			<string>\b(?:signals|delegate|reference)\b</string>
			<key>name</key>
			<string>keyword.control.ptl</string>
		</dict>
        <dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ptl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ptl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.ptl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escaped.ptl</string>
				</dict>
			</array>
		</dict>
        <dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ptl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ptl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.ptl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escaped.ptl</string>
				</dict>
			</array>
		</dict>
        <dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.ptl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.ptl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.ptl</string>
		</dict>
        <dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.ptl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.ptl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.name.type.ptl</string>
		</dict>
        <dict>
            <key>match</key>
            <string>\b([1-9][0-9]*)|([0-9]*\.[0-9]*)\b</string>
            <key>name</key>
            <string>constant.numeric</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(@[a-zA-Z0-9_-][\w-]*)</string>
            <key>name</key>
            <string>storage.type.ptl</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(\$[a-zA-Z0-9_-][\w-]*)</string>
            <key>name</key>
            <string>variable.other.ptl</string>
        </dict>
        <dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.ptl</string>
		</dict>
    </array>
    <key>scopeName</key>
	<string>source.ptl</string>
    <key>uuid</key>
    <string>FF0550E0-3A29-11E3-AA6E-0800200C9A77</string>
</dict>